### ISSUE TITLE
Can we get a sodium version?

### ISSUE THREAD

**Issue by om3ga6400** [DeeChael/EmbyUI#2]
that would be epic

**Comment by DeeChael** [comment]
actually, this project hasn't been maintained for months, i dont have time to work on any projects except my another mod Concentration due to my college studies

**Comment by om3ga6400** [comment]
> actually, this project hasn't been maintained for months, i dont have time to work on any projects except my another mod Concentration due to my college studies

what mod are you developing?

**Comment by DeeChael** [comment]
borderless fullscreen

**Comment by om3ga6400** [comment]
well if you ever get the time I think it would be really really cool if you ported this to work with sodium

**Comment by raspberrygitq** [comment]
If you are looking for an alternative to Sodium for this mod, I recommend these two mods  [Sodium Options API](https://modrinth.com/mod/sodium-options-api) and [Sodium Options Mod Compat](https://modrinth.com/mod/sodium-options-mod-compat)

**Comment by DeeChael** [comment]
according to @raspberrygitq's reply, seems that this issue can be closed.  
as I have no time to maintain this mod, SOMC is a better choice and its author did what I want but not do (porting Embeddium options ui to Sodium)
